remote_theme: mikearnaldi/just-the-docs
search_enabled: true
aux_links:
  "Docs":
    - "//effect-ts.github.io/platform"
  "API Reference":
    - "//effect-ts.github.io/platform/docs/platform"
  "GitHub":
    - "//github.com/effect-ts/platform"
